### ISSUE TITLE
mold fails to build with musl libc with undefined references to getcontext, swapcontext and makecontext

### ISSUE THREAD

**Issue by stefson** [rui314/mold#281]
hey, I tried to compile mold source code on a linux that uses musl as the libc. Its a very lean and fast alternative to the bloaty and unhealthy glibc. Here is the error, during linking: 

```
g++-10.3.0 -DMOLD_VERSION=\"1.0.1\" -DLIBDIR="\"/usr/lib\"" -O2 -pipe -pthread -fPIE -fno-unwind-tables -fno-asynchronous-unwind-tables -std=c++20 -fno-exceptions -Wl,-O1 -Wl,--as-needed  out/compress.o out/demangle.o out/filepath.o out/hyperloglog.o out/main.o out/perf.o out/tar.o out/elf/arch-arm64.o out/elf/arch-i386.o out/elf/arch-x86-64.o out/elf/cmdline.o out/elf/gc-sections.o out/elf/icf.o out/elf/input-sections.o out/elf/linker-script.o out/elf/main.o out/elf/mapfile.o out/elf/object-file.o out/elf/output-chunks.o out/elf/output-file.o out/elf/passes.o out/elf/relocatable.o out/elf/subprocess.o out/macho/arch-arm64.o out/macho/arch-x86-64.o out/macho/cmdline.o out/macho/dead-strip.o out/macho/dumper.o out/macho/input-sections.o out/macho/main.o out/macho/mapfile.o out/macho/object-file.o out/macho/output-chunks.o out/macho/output-file.o out/macho/tapi.o out/macho/yaml.o -o mold -pthread -lz -ldl -lm -lmimalloc -ltbb -lxxhash -lrt -lcrypto
/usr/lib/gcc/aarch64-gentoo-linux-musl/10.3.0/../../../../aarch64-gentoo-linux-musl/bin/ld: /usr/lib/gcc/aarch64-gentoo-linux-musl/10.3.0/../../../../lib/libtbb.so: undefined reference to `getcontext'
/usr/lib/gcc/aarch64-gentoo-linux-musl/10.3.0/../../../../aarch64-gentoo-linux-musl/bin/ld: /usr/lib/gcc/aarch64-gentoo-linux-musl/10.3.0/../../../../lib/libtbb.so: undefined reference to `swapcontext'
/usr/lib/gcc/aarch64-gentoo-linux-musl/10.3.0/../../../../aarch64-gentoo-linux-musl/bin/ld: /usr/lib/gcc/aarch64-gentoo-linux-musl/10.3.0/../../../../lib/libtbb.so: undefined reference to `makecontext'
collect2: error: ld returned 1 exit status
make: *** [Makefile:118: mold] Error 1
```

mold was build using these commands: 

```
make -j1 SYSTEM_TBB=1 SYSTEM_MIMALLOC=1 SYSTEM_XXHASH=1 STRIP=true LIBDIR=/usr/lib
```

do you have an idea where this is coming from? is it a bug in libtbb.so?

**Comment by stefson** [comment]
full buid log: [mold-aarch64-musl.log.zip](https://github.com/rui314/mold/files/7896234/mold-aarch64-musl.log.zip)

**Comment by rui314** [comment]
It looks like libtbb uses `getcontext` and so on that are not supported by musl. I guess all programs that use libtbb won't work with musl.

If you built tbb yourself (by removing `SYSTEM_TBB=1` from your make arguments), does it work?

**Comment by stefson** [comment]
interesting, it seems to work when building outside of the package manager: 

```
[100%] Built target tbb
make[3]: Leaving directory '/tmp/mold/out/tbb'
make[2]: Leaving directory '/tmp/mold/out/tbb'
make[1]: Leaving directory '/tmp/mold/out/tbb'
(cd out/tbb; ln -sf *_relwithdebinfo libs)
make -C third-party/xxhash libxxhash.a
make[1]: Entering directory '/tmp/mold/third-party/xxhash'
gcc-10.3.0 -O3 -Wall -Wextra -Wconversion -Wcast-qual -Wcast-align -Wshadow -Wstrict-aliasing=1 -Wswitch-enum -Wdeclaration-after-statement -Wstrict-prototypes -Wundef -Wpointer-arith -Wformat-security -Wvla -Wformat=2 -Winit-self -Wfloat-equal -Wwrite-strings -Wredundant-decls -Wstrict-overflow=2    -c -o xxhash.o xxhash.c
ar rcs libxxhash.a xxhash.o
make[1]: Leaving directory '/tmp/mold/third-party/xxhash'
g++-10.3.0 -DMOLD_VERSION=\"1.0.1\" -DLIBDIR="\"/usr/local/lib\"" -DGIT_HASH=\"cb2b4b8f724ed8b1b4665bc5c3134652d4031fd1\" -Ithird-party/mimalloc/include -Ithird-party/tbb/include -Ithird-party/xxhash -O2 -pthread -fPIE -fno-unwind-tables -fno-asynchronous-unwind-tables -std=c++20 -fno-exceptions   out/compress.o out/demangle.o out/filepath.o out/hyperloglog.o out/main.o out/perf.o out/tar.o out/elf/arch-arm64.o out/elf/arch-i386.o out/elf/arch-x86-64.o out/elf/cmdline.o out/elf/gc-sections.o out/elf/icf.o out/elf/input-sections.o out/elf/linker-script.o out/elf/main.o out/elf/mapfile.o out/elf/object-file.o out/elf/output-chunks.o out/elf/output-file.o out/elf/passes.o out/elf/relocatable.o out/elf/subprocess.o out/macho/arch-arm64.o out/macho/arch-x86-64.o out/macho/cmdline.o out/macho/dead-strip.o out/macho/dumper.o out/macho/input-sections.o out/macho/main.o out/macho/mapfile.o out/macho/object-file.o out/macho/output-chunks.o out/macho/output-file.o out/macho/tapi.o out/macho/yaml.o -o mold -pthread -lz -ldl -lm -Wl,-whole-archive out/mimalloc/libmimalloc.a -Wl,-no-whole-archive out/tbb/libs/libtbb.a third-party/xxhash/libxxhash.a -lrt -lcrypto
ln -sf mold ld
ln -sf mold ld64.mold
gcc-10.3.0 -DMOLD_VERSION=\"1.0.1\" -DLIBDIR="\"/usr/local/lib\"" -DGIT_HASH=\"cb2b4b8f724ed8b1b4665bc5c3134652d4031fd1\" -Ithird-party/mimalloc/include -Ithird-party/tbb/include -Ithird-party/xxhash -O2 -pthread -fPIE -fno-unwind-tables -fno-asynchronous-unwind-tables -fPIC -shared -o mold-wrapper.so  elf/mold-wrapper.c -ldl[100%] Built target tbb
make[3]: Leaving directory '/tmp/mold/out/tbb'
make[2]: Leaving directory '/tmp/mold/out/tbb'
make[1]: Leaving directory '/tmp/mold/out/tbb'
(cd out/tbb; ln -sf *_relwithdebinfo libs)
make -C third-party/xxhash libxxhash.a
make[1]: Entering directory '/tmp/mold/third-party/xxhash'
gcc-10.3.0 -O3 -Wall -Wextra -Wconversion -Wcast-qual -Wcast-align -Wshadow -Wstrict-aliasing=1 -Wswitch-enum -Wdeclaration-after-statement -Wstrict-prototypes -Wundef -Wpointer-arith -Wformat-security -Wvla -Wformat=2 -Winit-self -Wfloat-equal -Wwrite-strings -Wredundant-decls -Wstrict-overflow=2    -c -o xxhash.o xxhash.c
ar rcs libxxhash.a xxhash.o
make[1]: Leaving directory '/tmp/mold/third-party/xxhash'
g++-10.3.0 -DMOLD_VERSION=\"1.0.1\" -DLIBDIR="\"/usr/local/lib\"" -DGIT_HASH=\"cb2b4b8f724ed8b1b4665bc5c3134652d4031fd1\" -Ithird-party/mimalloc/include -Ithird-party/tbb/include -Ithird-party/xxhash -O2 -pthread -fPIE -fno-unwind-tables -fno-asynchronous-unwind-tables -std=c++20 -fno-exceptions   out/compress.o out/demangle.o out/filepath.o out/hyperloglog.o out/main.o out/perf.o out/tar.o out/elf/arch-arm64.o out/elf/arch-i386.o out/elf/arch-x86-64.o out/elf/cmdline.o out/elf/gc-sections.o out/elf/icf.o out/elf/input-sections.o out/elf/linker-script.o out/elf/main.o out/elf/mapfile.o out/elf/object-file.o out/elf/output-chunks.o out/elf/output-file.o out/elf/passes.o out/elf/relocatable.o out/elf/subprocess.o out/macho/arch-arm64.o out/macho/arch-x86-64.o out/macho/cmdline.o out/macho/dead-strip.o out/macho/dumper.o out/macho/input-sections.o out/macho/main.o out/macho/mapfile.o out/macho/object-file.o out/macho/output-chunks.o out/macho/output-file.o out/macho/tapi.o out/macho/yaml.o -o mold -pthread -lz -ldl -lm -Wl,-whole-archive out/mimalloc/libmimalloc.a -Wl,-no-whole-archive out/tbb/libs/libtbb.a third-party/xxhash/libxxhash.a -lrt -lcrypto
ln -sf mold ld
ln -sf mold ld64.mold
gcc-10.3.0 -DMOLD_VERSION=\"1.0.1\" -DLIBDIR="\"/usr/local/lib\"" -DGIT_HASH=\"cb2b4b8f724ed8b1b4665bc5c3134652d4031fd1\" -Ithird-party/mimalloc/include -Ithird-party/tbb/include -Ithird-party/xxhash -O2 -pthread -fPIE -fno-unwind-tables -fno-asynchronous-unwind-tables -fPIC -shared -o mold-wrapper.so  elf/mold-wrapper.c -ldl
```

I see some warnings in cmake: 

```
-- Detecting CXX compile features - done
CMake Warning at CMakeLists.txt:109 (message):
  You are building oneTBB as a static library.  This is highly discouraged
  and such configuration is not supported.  Consider building a dynamic
  library to avoid unforeseen issues.
```

do you demand the static libs to link against instead of the dynamic libs, in case of system-libs for minimalloc and tbb? 

full log: [compile-log-mold-aarch64.log.zip](https://github.com/rui314/mold/files/7896834/compile-log-mold-aarch64.log.zip)

**Comment by rui314** [comment]
I believe your system-wide libtbb is not compiled against musl. musl and glibc are not ABI-compatible, and I don't think you can load glibc and musl simultaneously to the same process. So, unless all of your libraries were built agaisnst musl, it is not supposed to work if you link only the main executable to musl.

**Comment by stefson** [comment]
This is of course a whole userland build with, and against musl as the libc. 

The system libtbb.so is seemingly broken with missing symbols, thats for sure.

**Comment by Alcaro** [comment]
Sounds like someone forgot the -Wl,--no-undefined on TBB. I can think of a few usecases for allowing dangling links (Python modules that want to be usable in both python3.9 and python3.10, for example), but why is no-undefined not the default?

Searching for getcontext reveals the single file https://github.com/rui314/mold/blob/main/third-party/tbb/src/tbb/co_context.h. Searching for its used symbols reveals the single file https://github.com/rui314/mold/blob/main/third-party/tbb/src/tbb/task.cpp. Since it compiles correctly with static TBB, the relevant object file is clearly unused.

Proposed solution: Poke https://github.com/rui314/mold/blob/fea59750ed50a2233f13eadfdcc27880da4a6c93/third-party/tbb/include/oneapi/tbb/detail/_config.h#L271 a little. Either disable it under musl, or just hardcode it to false.

**Comment by rui314** [comment]
I want to fix the upstream rather than applying a local patch. Do you want to do that?

**Comment by stefson** [comment]
I will try to work on a solution for libtbb with the fellow gentoo-dev, I'm not exactly competent enough to tackle this all by myself.

**Comment by rui314** [comment]
I believe I can fix the problem by telling the linker to not handle unresolved symbols in shared libraries as errors. I can do that by specifying `--allow-shlib-undefined`. This isn't a proper fix, as your libtbb world fail at runtime if someone tries to use that symbol, but for mold, that's not an issue.

**Comment by Alcaro** [comment]
Yep, that's making TBB throw an error rather than silently emit a corrupt .so. Clear improvement.

But yeah, it needs a real fix too.

**Comment by rui314** [comment]
@stefson You may want to report that to Gentoo's package owner of libtbb, as it looks like adding `-Wl,--no-undefined` is recommended at [Gentoo wiki](https://wiki.gentoo.org/wiki/Project:Quality_Assurance/-Wl,-z,defs_and_-Wl,--no-allow-shlib-undefined).

**Comment by stefson** [comment]
I emerged mold from latest git commit, which includes your fix. This makes it compile, but the binary is not useable: 

```
ldd /usr/bin/mold 
        /lib/ld-musl-aarch64.so.1 (0x7faa5c7000)
        libz.so.1 => /lib/libz.so.1 (0x7faa311000)
        libmimalloc.so.2.0 => /usr/lib/libmimalloc.so.2.0 (0x7faa275000)
        libtbb.so.12 => /usr/lib/libtbb.so.12 (0x7faa224000)
        libcrypto.so.1.1 => /usr/lib/libcrypto.so.1.1 (0x7fa9f9a000)
        libstdc++.so.6 => /usr/lib/gcc/aarch64-gentoo-linux-musl/10.3.0/libstdc++.so.6 (0x7fa9dc0000)
        libc.so => /lib/ld-musl-aarch64.so.1 (0x7faa5c7000)
        libgcc_s.so.1 => /usr/lib/gcc/aarch64-gentoo-linux-musl/10.3.0/libgcc_s.so.1 (0x7fa9d9c000)
Error relocating /usr/lib/libtbb.so.12: swapcontext: symbol not found
Error relocating /usr/lib/libtbb.so.12: getcontext: symbol not found
Error relocating /usr/lib/libtbb.so.12: makecontext: symbol not found
```

**Comment by rui314** [comment]
I think there are two possibilities.

1. mold actually uses these functions at runtime, or
2. your mold is linked with `-z now` to force resolve all dynamic symbols at program start-up time

Please paste the output of `readelf -d mold`. If `NOW` is in the output, your mold is built with `-z now`.

**Comment by stefson** [comment]
sure, here is the output of `readelf -d /usr/bin/mold`

```
Dynamic section at offset 0x27bc98 contains 31 entries:
  Tag        Type                         Name/Value
 0x0000000000000001 (NEEDED)             Shared library: [libz.so.1]
 0x0000000000000001 (NEEDED)             Shared library: [libmimalloc.so.2.0]
 0x0000000000000001 (NEEDED)             Shared library: [libtbb.so.12]
 0x0000000000000001 (NEEDED)             Shared library: [libcrypto.so.1.1]
 0x0000000000000001 (NEEDED)             Shared library: [libstdc++.so.6]
 0x0000000000000001 (NEEDED)             Shared library: [libc.so]
 0x000000000000000c (INIT)               0x250d0
 0x000000000000000d (FINI)               0x2442d0
 0x0000000000000019 (INIT_ARRAY)         0x27f890
 0x000000000000001b (INIT_ARRAYSZ)       296 (bytes)
 0x000000000000001a (FINI_ARRAY)         0x27f9b8
 0x000000000000001c (FINI_ARRAYSZ)       8 (bytes)
 0x000000006ffffef5 (GNU_HASH)           0x258
 0x0000000000000005 (STRTAB)             0x1ae8
 0x0000000000000006 (SYMTAB)             0x330
 0x000000000000000a (STRSZ)              7276 (bytes)
 0x000000000000000b (SYMENT)             24 (bytes)
 0x0000000000000015 (DEBUG)              0x0
 0x0000000000000003 (PLTGOT)             0x28bfe8
 0x0000000000000002 (PLTRELSZ)           4872 (bytes)
 0x0000000000000014 (PLTREL)             RELA
 0x0000000000000017 (JMPREL)             0x23dc8
 0x0000000000000007 (RELA)               0x3a70
 0x0000000000000008 (RELASZ)             131928 (bytes)
 0x0000000000000009 (RELAENT)            24 (bytes)
 0x000000006ffffffb (FLAGS_1)            Flags: PIE
 0x000000006ffffffe (VERNEED)            0x3950
 0x000000006fffffff (VERNEEDNUM)         3
 0x000000006ffffff0 (VERSYM)             0x3754
 0x000000006ffffff9 (RELACOUNT)          4621
 0x0000000000000000 (NULL)               0x0
```

**Comment by rui314** [comment]
OK, there's no `NOW` in the output, so I believe mold actually needs these functions at runtime. That means libtbb might be simply incompatible with musl and needs to remove the dependency to glibc-specific functions to make it work with musl.

**Comment by Alcaro** [comment]
> I believe mold actually needs these functions at runtime

I don't think so. It works if linked statically, meaning the relevant object file is unreachable from mold. Maybe musl's loader hardcodes the NOW behavior even if the executable isn't flagged as such?

> glibc-specific functions

It's not glibc specific, it's in POSIX.

Or rather, [it _was_ in POSIX](https://linux.die.net/man/3/swapcontext).

> Conforming To
> SUSv2, POSIX.1-2001. POSIX.1-2008 removes the specifications of makecontext() and swapcontext(), citing portability issues, and recommending that applications be rewritten to use POSIX threads instead.  

Anyways, if the polite solutions don't work, how about a terrible bruteforce solution?

```c
extern "C" __attribute__((__visibility__("default"))) int getcontext(ucontext_t* ucp) { __builtin_trap(); }
extern "C" __attribute__((__visibility__("default"))) int setcontext(const ucontext_t* ucp) { __builtin_trap(); }
extern "C" __attribute__((__visibility__("default"))) void makecontext(ucontext_t* ucp, void (*func)(), int argc, ...) { __builtin_trap(); }
extern "C" __attribute__((__visibility__("default"))) int swapcontext(ucontext_t* oucp, ucontext_t* ucp) { __builtin_trap(); }
```

(Why does TBBs object file compile? Does musl declare the functions in headers, but not actually implement them?)

**Comment by rui314** [comment]
Looks like the following features are enabled on Gentoo with musl according to https://wiki.gentoo.org/wiki/Project:Musl

> - Stack Smashing Protection (SSP), which requires threads but doesn't work with the old NPTL or LinuxThreads that uClibc provides.
> - Position Independent Execution (PIE).
> - Bind now and relro, linker hardening to protect the global offset table.

I really think that this shouldn't be fixed in mold but in Gentoo's libtbb's package. If Bind Now is enabled by default, no one can use libtbb.so in that environment.

**Comment by thesamesam** [comment]
I think TBB is underlinked and we need to force linking against libucontext for musl.

**Comment by stefson** [comment]
Can you think of reverting you attempt in https://github.com/rui314/mold/commit/2cc85cc21dbb4ee014631327e10f5ef21bad7c62 to fix this? 

It really seems libtbb.so needs to be fixed here, no need to add complexity before that hasn't happend.

**Comment by rui314** [comment]
Yes, I'll revert that change. Thank you for you suggestion.

**Comment by thesamesam** [comment]
I still see this problem even when TBB is linked against `libucontext`:
```
# lddtree /usr/lib/libtbb.so.12.5
libtbb.so.12.5 => /usr/lib/libtbb.so.12.5 (interpreter => none)
    libucontext.so.1 => /usr/lib/libucontext.so.1
    libstdc++.so.6 => /usr/lib/gcc/x86_64-gentoo-linux-musl/11.2.1/libstdc++.so.6
    libgcc_s.so.1 => /usr/lib/gcc/x86_64-gentoo-linux-musl/11.2.1/libgcc_s.so.1
    libc.so => /usr/lib/libc.so
```

```
x86_64-gentoo-linux-musl-g++ -DMOLD_VERSION=\"1.0.1\" -DLIBDIR="\"/usr/lib\"" -O2 -pipe -march=native -pthread -fPIE -fno-unwind-tables -fno-asynchronous-unwind-tables -std=c++20 -fno-exceptions -Wl,-O1 -Wl,--as-needed  out/compress.o out/demangle.o out/filepath.o out/hyperloglog.o out/main.o out/perf.o out/tar.o out/elf/arch-arm64.o out/elf/arch-i386.o out/elf/arch-x86-64.o out/elf/cmdline.o out/elf/gc-sections.o out/elf/icf.o out/elf/input-sections.o out/elf/linker-script.o out/elf/main.o out/elf/mapfile.o out/elf/object-file.o out/elf/output-chunks.o out/elf/output-file.o out/elf/passes.o out/elf/relocatable.o out/elf/subprocess.o out/macho/arch-arm64.o out/macho/arch-x86-64.o out/macho/cmdline.o out/macho/dead-strip.o out/macho/dumper.o out/macho/input-sections.o out/macho/main.o out/macho/mapfile.o out/macho/object-file.o out/macho/output-chunks.o out/macho/output-file.o out/macho/tapi.o out/macho/yaml.o -o mold -pthread -lz -ldl -lm -lmimalloc -ltbb -lxxhash -lrt -lcrypto
/usr/lib/gcc/x86_64-gentoo-linux-musl/11.2.1/../../../../x86_64-gentoo-linux-musl/bin/ld: /usr/lib/gcc/x86_64-gentoo-linux-musl/11.2.1/../../../../lib/libtbb.so: undefined reference to `getcontext'
/usr/lib/gcc/x86_64-gentoo-linux-musl/11.2.1/../../../../x86_64-gentoo-linux-musl/bin/ld: /usr/lib/gcc/x86_64-gentoo-linux-musl/11.2.1/../../../../lib/libtbb.so: undefined reference to `swapcontext'
/usr/lib/gcc/x86_64-gentoo-linux-musl/11.2.1/../../../../x86_64-gentoo-linux-musl/bin/ld: /usr/lib/gcc/x86_64-gentoo-linux-musl/11.2.1/../../../../lib/libtbb.so: undefined reference to `makecontext'
collect2: error: ld returned 1 exit status
make: *** [Makefile:118: mold] Error 1
 * ERROR: sys-devel/mold-1.0.1-r1::gentoo failed (compile phase):
 *   emake failed
```

I think it's because libucontext's symbols are prefixed:
```
# nm -D /usr/lib/libucontext.so.1
                 w _ITM_deregisterTMCloneTable
                 w _ITM_registerTMCloneTable
                 w __cxa_finalize
                 w __deregister_frame_info
                 w __register_frame_info
                 U __stack_chk_fail
0000000000001611 T _fini
0000000000001000 T _init
                 U exit
000000000000145a T libucontext_getcontext
00000000000011d0 T libucontext_makecontext
00000000000014bc T libucontext_setcontext
0000000000001514 T libucontext_swapcontext
```

Not sure how to make TBB use them.

**Comment by andrewathalye** [comment]
[mold-1.0.2-musl-libucontext.patch.txt](https://github.com/rui314/mold/files/8000105/mold-1.0.2-musl-libucontext.patch.txt)
Attached is a simple patch that can be put in /etc/portage/patches/sys-devel/mold, etc. in order to use libucontext when available.
As @thesamesam noted above, this does not currently work on Gentoo due to an issue with libucontext's Makefile that causes it to fail to include unprefixed (weak) symbols whenever Gentoo specifies its own CFLAGS. The relevant issue can be viewed here: https://github.com/kaniini/libucontext/issues/39 . A patch is attached there allowing libucontext to work properly on Gentoo musl as well.

**Comment by andrewathalye** [comment]
Hopefully this explains some of the strange behaviour observed here earlier. The seemingly missing symbols in the ebuild version of libucontext look to be caused by the UNPREFIXED_SYMBOLS option being handled in CFLAGS, meaning that it was regularly overwritten by the CFLAGS contained in make.conf. Issues have also been made in the Gentoo Bugzilla to handle this. As for where -lucontext would be best to put, it could be included in mold itself, but oneTBB would probably be a better place since the symbols are needed there as well (although it _builds_ without them).

**Comment by rui314** [comment]
@andrewathalye I already applied a local path to the libtbb included in our repo and should compile on musl-based Linux systems. If getcontext()-family functions aren't available, it looks like we can just disable TBB features that depend on it rather than linking against libucontext. I already sent a patch to TBB (https://github.com/oneapi-src/oneTBB/pull/748/files).

**Comment by rui314** [comment]
My fix to upstream has been merged (https://github.com/oneapi-src/oneTBB/pull/748), so since the next release, oneTBB should compile with musl out of the box.

**Comment by andrewathalye** [comment]
Great. I just checked on a fresh clone of main and it compiles and works as expected on musl gentoo. It may be necessary to backport the tbb patches on Gentoo until oneTBB makes a new release, but otherwise the situation looks good.

**Comment by andrewathalye** [comment]
I've closed the Gentoo issue as "resolved upstream" and made one for libucontext and oneTBB instead, since those are where builds are currently failing. Thanks for the insight and patches. This issue will probably be safe to close as soon as oneTBB releases a version with the fixes and it is incorporated into Gentoo.

**Comment by stefson** [comment]
@andrewathalye did you do runtime tests with mold in gentoo, actually? I keep hitting runtime errors, with this fix included of course.

**Comment by thesamesam** [comment]
> @andrewathalye did you do runtime tests with mold in gentoo, actually? I keep hitting runtime errors, with this fix included of course.

Which fix? What errors?

It could be:
- the libucontext change
- the TBB change
- forcing TBB to link against libucontext once changed

**Comment by stefson** [comment]
I added the fix for libtbb.so and recompiled tbb and mold, don't think there was anything posted with regard on how to force to link libtbb.so against libucontext. 

here is the error: 

```
mimalloc: warning: unable to allocate OS memory (67108864 bytes, error code: 12, address: 0, large only: 0, allow large: 1)
mimalloc: warning: unable to allocate OS memory (67108864 bytes, error code: 12, address: 0, large only: 0, allow large: 1)
mimalloc: warning: unable to allocate OS memory (67108864 bytes, error code: 12, address: 0, large only: 0, allow large: 1)
mimalloc: warning: unable to allocate OS memory (67108864 bytes, error code: 12, address: 0, large only: 0, allow large: 1)
mimalloc: error: unable to allocate memory (72704 bytes)
mimalloc: warning: unable to allocate OS memory (67108864 bytes, error code: 12, address: 0, large only: 0, allow large: 1)
mimalloc: warning: unable to allocate OS memory (67108864 bytes, error code: 12, address: 0, large only: 0, allow large: 1)
mimalloc: warning: unable to allocate OS memory (67108864 bytes, error code: 12, address: 0, large only: 0, allow large: 1)
mimalloc: warning: unable to allocate OS memory (67108864 bytes, error code: 12, address: 0, large only: 0, allow large: 1)
mimalloc: error: unable to allocate memory (36 bytes)
mimalloc: error: out of memory in 'new'Aborted
```

(its on aarch64)

**Comment by andrewathalye** [comment]
> @andrewathalye did you do runtime tests with mold in gentoo, actually? I keep hitting runtime errors, with this fix included of course.

Yes. On my x86_64 musl system using TBB with the no-getcontext/makecontext/setcontext patch applied (https://bugs.gentoo.org/832700) I am able to emerge and use mold as expected, at least for simple programs. I have not tried using it systemwide yet, but I was able to link an example C++ and C program manually by invoking it with the appropriate objects. The resulting executable worked as expected.

In the end I decided not to use the libucontext setup, since oneTBB already has full support for not using the deprecated context functions and libucontext currently has its own issues with the Gentoo build system due to how it passes configuration flags and how the ebuild is currently setup.

**Comment by andrewathalye** [comment]
I could set up an aarch64 musl chroot to try it out, but I don't have performant arm hardware so I can't really say whether that would be a useful test.

**Comment by stefson** [comment]
thanks but not needed, I fetchted an amd64 stage3 and compiled mold there. A simple `mold -v` is working here, thats enough for me to confirm the tbb patch working.

**Comment by thesamesam** [comment]
> I added the fix for libtbb.so and recompiled tbb and mold, don't think there was anything posted with regard on how to force to link libtbb.so against libucontext.
> 

[It was on Gentoo's Bugzilla](https://bugs.gentoo.org/832676).

Anyway, hopefully the *context / TBB parts are fixed now, but not sure what the malloc/allocation issues are for you, but it's progress :)

**Comment by rui314** [comment]
I don't have an ARM64 machine, but let me fire up one on EC2 to see if I can reproduce the issue. Is Gentoo ARM64 musl available as a docker image?

**Comment by stefson** [comment]
I'm uncertain wether there is a docker image available, actually don't know nothing about docker container and all this, sorry. Maybe sam knows more about it. 

My workflow of testing this is grabbing a stage3 and chrooting into, there is qemu-static kungfu for the adventurous :)

**Comment by stefson** [comment]
@rui314 were you able to get an ARM64 musl image to work with? 

If not, I can try to ask gentoo/gentoo-docker-images crowd to add it for you?

**Comment by stefson** [comment]
Its just I don't know who to ask for help with providing the docker image, certainly I have not any idea about the whole container stuff :-/  

@thesamesam can you help us out with how to provide an aarch64-musl docker image?

**Comment by stefson** [comment]
@rui314 there is now an arm64-musl gentoo image available, are you able to work with it?

**Comment by rui314** [comment]
Sure, let me do that before v1.1.1.

**Comment by rui314** [comment]
@stefson Looks like mimalloc does not work correctly on aarch64/musl. Please disable it by building mold with `make USE_MIMALLOC=0`.

**Comment by stefson** [comment]
yes, that builds me a /usr/bin/mold which doesn't flake when I fire up `mold -v`

what are the consequences though of removing mimalloc support?

**Comment by Alcaro** [comment]
Removing mimalloc makes it slower. Everything else remains the same.

**Comment by rui314** [comment]
Right. It only affects performance of the linker. 

So the issue is not specific to mold. I believe mimalloc is just unusable on ARM64 if combined with musl. Can you report it to mimalloc?

**Comment by stefson** [comment]
I opened a ticket on their github, feel free to comment on it if you have any additional informations.

**Comment by daanx** [comment]
Just wanted to comment that the mimalloc issue here (with musl libc on arm64) was due to the older version of mimalloc in the mold `thirdparty/mimalloc` source. Updating to v2.0.5 fixes the issue.

Thanks for `mold`! and great to see mimalloc improved the performance further :-)

**Comment by stefson** [comment]
@rui314 I can confirm that rebuilding mold against mimalloc-2.0.5 solves the memory mapping issue, so it should be sufficent to update your internal fork in `third_party/mimalloc` to 2.0.5 to fix this issue for good.

**Comment by rui314** [comment]
Thank you for the info. I updated the mimalloc subtree to v2.0.5 in the above commit.
